### ISSUE TITLE
TOMOYO - the alternative to SElinux?!

### ISSUE THREAD

**Issue by Atavic** [CHEF-KOCH/Android-Vulnerabilities-Overview#6]
There's really little information about it, but Android kernel can be hardened with [Tomoyo Linux](http://tomoyo.osdn.jp/).
Android sources list Tomoyo under Common Android Kernel Tree, [Security Folder](https://android.googlesource.com/kernel/common/+/android-4.9/security/tomoyo/).

I have TOMOYO (a security module for system analisys and protection) installed on CentOS and I can tell that's really powerful. I hope someone running android gives Tomoyo a try, as some [modded kernels](https://github.com/Stuxnet-Kernel/stuxnet_cancro) contain it.

**Comment by Atavic** [comment]
[Tomoyo Linux](https://osdn.net/projects/tomoyo/) is a Mandatory Access Configuration that acts at the kernel level. Some similar [security modules](http://www.linuxquestions.org/questions/2015-linuxquestions-org-members-choice-awards-117/host-security-application-of-the-year-4175562719/) are SELinux, Apparmor or Smack.

Particularly, [Tomoyo Linux](http://linux.kernel.narkive.com/mo9V9khc/tomoyo-7-01-30-tomoyo-linux-documentation) can authorize:
+ TCP/IP networking operations based on IPv4/v6 addresses and port numbers.

It is well supported on [Arch Linux](https://wiki.archlinux.org/index.php/TOMOYO_Linux) and can be implemented on [other distros](https://pkgs.org/download/tomoyo) as Chakra Linux.

**Comment by CHEF-KOCH** [comment]
I think this also should mentioned and discussed internal with Google. Android itself uses SeDalvik (Android <5) / ART with [SELinux](https://source.android.com/security/selinux/concepts) since Android 4.3+. The government also uses SELinux (for a reason) instead of grpsecurity or appamor. Since I don't much about TOMOYO I can't really answer on this.

I'm simply not qualified enough to say what's 'the best' but could you explain why you want to replace SELinux with TOMOYO?! Otherwise this only can be mentioned as 'alternative' to the current implemented solution.

**Comment by Atavic** [comment]
Yes, as an alternative option. I'll look at the Android custom image ROM building community: https://forum.xda-developers.com/

**Comment by CHEF-KOCH** [comment]
SELinux, Tomoyo, AppArmor, grsecurity & Smack - all of those systems rely on setting up a catalogue of rules. Those rules define finer-grained access policies for files and system resources and thus provide increased security.

While Tomoyo, grsecurity and AppAmor are based on restricting file based rules, there weaker than SeLinux or Smack because such systems are working based on file paths (pathnames) which identify the files in the rules.

Advantage is that you can have cleaner and more understandable policy specified in the single place, and you don't have complications of xattrs spreading over whole filesystem. Think ability, I say, which is important. Disadvantage is that some implementations are not able to handle hardlinking or rename in easy for users way. However, [Tomoyo not answers all questions](http://tomoyo.osdn.jp/wiki-e/?WhatIs#g6a56098).

https://www.cyberciti.biz/tips/selinux-vs-apparmor-vs-grsecurity.html


So I'm gonna close this, because SELinux is totally fine, the real alternative would be (imho) only AppAmor and this has especially on mobile devices still problems, which overall means there is only SeLinux left.
